sudo: required
language: java
jdk: oraclejdk11

services:
  - postgresql

before_install:
  - chmod +x mvnw

script:
  - cd pharmacies
  - mvn clean install

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: pharmacies