sudo: required
language: java
jdk: oraclejdk11

services:
  - postgresql

addons:
  sonarcloud:
  organization: isa-tim28
  token: $SONAR_TOKEN

script:
  - cd pharmacies
  - mvn clean install
  - mvn sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=isa-tim28 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: pharmacies-backend